name: Test Interpreter

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build FiMsharp.Test --no-restore -c Release
            - name: Test
              run: dotnet run --project FiMSharp.Test -c Release
